---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm
    transport:
      name: winrm

suites:
  - name: all
    run_list:
      - recipe[workstation-windows::default]
      - recipe[workstation-windows::setup_test_environment]
