---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: win2012

suites:
  - name: setup_test_environment
    run_list:
      - recipe[workstation_windows::setup_test_environment]
