---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: mwrock/Windows2012R2
    transport:
      name: winrm

suites:
  - name: all
    run_list:
      - recipe[workstation-windows::default]
      - recipe[workstation-windows::install_applications]
      - recipe[workstation-windows::install_games]
      - recipe[workstation-windows::install_unity]
      - recipe[workstation-windows::setup_test_environment]
