---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: win2012
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[workstation-windows]
