name 'workstation-windows'
maintainer 'Brian Holtkamp'
maintainer_email 'brholtkamp@gmail.com'
license 'MIT'
description 'Installs and configures Windows workstations'
long_description 'A collection of recipes to setup different Windows environments to handle different tasks'
version '0.1.3'
supports 'windows'
source_url 'https://github.com/brholtkamp/workstation-windows'
issues_url 'https://github.com/brholtkamp/workstation-windows/issues'

depends 'chocolatey'
depends 'msys2'
depends 'vagrant'
depends 'windows'
depends 'workstation-common'
